CREATE TABLE Player (
  DiscordID   BIGINT      NOT NULL PRIMARY KEY,
  OsuID       INT         NOT NULL UNIQUE,
  OsuName     VARCHAR(16) NOT NULL,
  GlobalRank  INT         NOT NULL,
  CountryRank INT         NOT NULL,
  Level       FLOAT       NOT NULL,
  RawPP       FLOAT       NOT NULL,
  Accuracy    FLOAT       NOT NULL,
  PlayCount   INT         NOT NULL,

  CountX      INT,
  CountS      INT,
  CountA      INT,

  Count300    INT,
  Count100    INT,
  Count50     INT,

  Modes       SMALLINT    NOT NULL DEFAULT 1,

  LastUpdated BIGINT      NOT NULL
);

CREATE TABLE Guild (
  GuildID BIGINT      NOT NULL PRIMARY KEY,
  Prefix  VARCHAR(16) NOT NULL,
  Modules BIGINT      NOT NULL
);

CREATE TABLE Chart (
  ChartID INT         NOT NULL PRIMARY KEY         GENERATED BY DEFAULT AS IDENTITY
                                                     ( START WITH 2001, INCREMENT BY 1),
  Name    VARCHAR(32) NOT NULL,
  IsSet   BOOLEAN     NOT NULL                     DEFAULT TRUE
);

CREATE TABLE ChartMap (
  ChartID  INT NOT NULL,
  MapSetID INT NOT NULL,
  CONSTRAINT ChartMap_PK PRIMARY KEY (ChartId, MapSetId),
  CONSTRAINT ChartId_FK FOREIGN KEY (ChartId) REFERENCES Chart (ChartId)
);

CREATE TABLE GuildChart (
  GuildID BIGINT NOT NULL,
  ChartID INT    NOT NULL,
  CONSTRAINT GuildChart_PK PRIMARY KEY (GuildID, ChartID),
  CONSTRAINT GuildID_FK FOREIGN KEY (GuildID) REFERENCES GUILD (GuildID),
  CONSTRAINT ChartID_FK2 FOREIGN KEY (ChartID) REFERENCES CHART (ChartID)
);

CREATE TABLE GuildPlayer (
  GuildID   BIGINT   NOT NULL,
  DiscordID BIGINT   NOT NULL,
  Mode      SMALLINT NOT NULL,
  CONSTRAINT GuildPlayer PRIMARY KEY (DiscordID, GuildID, Mode),
  CONSTRAINT DiscordID_FK FOREIGN KEY (DiscordID) REFERENCES Player (DiscordID),
  CONSTRAINT GuildID_FK2 FOREIGN KEY (GuildID) REFERENCES GUILD (GuildID)
);


CREATE TABLE ChannelMode (
  ChannelID BIGINT   NOT NULL,
  GuildID   BIGINT   NOT NULL,
  Mode      SMALLINT NOT NULL,
  CONSTRAINT ChannelMode PRIMARY KEY (ChannelID),
  CONSTRAINT GuildID_FK3 FOREIGN KEY (GuildID) REFERENCES Guild (GuildID)
);

CREATE TABLE ChannelLock (
  GuildID   BIGINT NOT NULL,
  ChannelID BIGINT NOT NULL,
  CONSTRAINT ChannelLock_PK PRIMARY KEY (GuildID, ChannelID),
  CONSTRAINT GUILDID_FK4 FOREIGN KEY (GuildID) REFERENCES Guild (GuildID)
);

CREATE TABLE MapSet (
  MapID INT NOT NULL,
  SetID INT NOT NULL,
  CONSTRAINT MapSet_PK PRIMARY KEY (MapID)
);